when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false

    framework:
        profiler:
            enabled: true
            collect: true
            only_main_requests: true

when@test:
    framework:
        profiler: { collect: false }